config/routes.rb
Session4::Application.routes.draw do
  resources :events

  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]

  root :to => "pages#home"

  match 'about' => 'pages#about'

  resources :users

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  starts_at      :datetime
#  ends_at        :datetime
#  street_address :string(255)
#  city           :string(255)
#  state          :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Event < ActiveRecord::Base
  attr_accessible :city, :ends_at, :starts_at, :state, :street_address, :user_id
  
  belongs_to :user

  validates :user_id, :presence => true
  validates :street_address, :presence => true, :length => { :maximum => 100 }
  validates :city, :presence => true, :length => { :maximum => 25 }
  validates :state, :presence => true, :length => { :maximum => 2 }
  validates :starts_at, :presence => true
  validates :ends_at, :presence => true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  has_many :events

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :logged_in_user, only: [:new, :create, :index]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = current_user.events.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def logged_in_user
    redirect_to signin_path unless signed_in?
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:session][:email].downcase)
	  if user && user.authenticate(params[:session][:password])
	    sign_in user
	  else
      flash[:error] = "Something went wrong. Please try again."
	    redirect_to signin_path
	  end
  end

  def destroy
  	sign_out
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        flash[:success] = "Thanks for joining Easy Meetings!"
        format.html { redirect_to @user }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active_page(path)
		%q( class="active").html_safe if current_page?(path)
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		session[:remember_token] = user.id
		self.current_user = User.find(session[:remember_token])
	end

	def sign_out
		@current_user = nil
		reset_session
	end

	def current_user=(user)
    @current_user = user
  end

  def current_user
  	@current_user ||= User.find(session[:remember_token]) unless session[:remember_token].nil?
	end

	def signed_in?
		!current_user.nil?
	end

	def same_user?(user)
		redirect_to(root_path) unless current_user?(user)
	end

	def current_user?
		user == current_user
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<p>
  <b>Starts at:</b>
  <%= event.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= event.ends_at %>
</p>

<p>
  <b>Street address:</b>
  <%= event.street_address %>
</p>

<p>
  <b>City:</b>
  <%= event.city %>
</p>

<p>
  <b>State:</b>
  <%= event.state %>
</p>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :starts_at %>
    <div class="row">
      <div class="span4">
        <%= f.date_select :starts_at, {}, {:class => 'input-small'} %>
      </div>
      <div class="span3">
        <%= f.time_select :starts_at, {:default => {:hour => 9, :minute => 00}, :ampm => true, :minute_step => 15}, {:class => "input-small"} %>
      </div>
    </div>
    <%= f.label :ends_at %>
    <div class="row">
      <div class="span4">
        <%= f.date_select :ends_at, {}, {:class => 'input-small'} %>
      </div>
      <div class="span3">
        <%= f.time_select :ends_at, {:default => {:hour => 10, :minute => 00}, :ignore_date => true, :ampm => true, :minute_step => 15}, {:class => "input-small"} %>
      </div>
    </div>

    <%= f.label :street_address %>
    <%= f.text_field :street_address %>

    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :state %>
    <%= f.text_field :state %>

    <div class="clear"></div><%= f.submit class: "btn btn-large btn-primary" %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>User</th>
    <th>Starts at</th>
    <th>Ends at</th>
    <th>Street address</th>
    <th>City</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.user_id %></td>
    <td><%= event.starts_at %></td>
    <td><%= event.ends_at %></td>
    <td><%= event.street_address %></td>
    <td><%= event.city %></td>
    <td><%= event.state %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @event.user_id %>
</p>

<p>
  <b>Starts at:</b>
  <%= @event.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @event.ends_at %>
</p>

<p>
  <b>Street address:</b>
  <%= @event.street_address %>
</p>

<p>
  <b>City:</b>
  <%= @event.city %>
</p>

<p>
  <b>State:</b>
  <%= @event.state %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<%= debug(params) if Rails.env.development? %>
	<%= debug(flash) if Rails.env.development? %>
	<%= current_user.name unless !signed_in? %>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">Easy Meetings</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li<%= active_page(root_path) %>><%= link_to "Home", root_path %></li>
          <li<%= active_page(about_path) %>><%= link_to "About", about_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Sign out", signout_path %></li>
          <% else %>
            <li<%= active_page(signin_path) %>><%= link_to "Sign in", signin_path %></li>
            <li<%= active_page(new_user_path) %>><%= link_to "Sign up", new_user_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Session4</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <div class="clear"></div><%= f.submit class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Signup for Easy Meetings</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<%= render @user.events %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>